### PR TITLE
[TestBot][Linux] Deploy on Azure using Azure Pipelines

### PR DESCRIPTION
**Pull request by ParadoxARG**
This PR is based on #47 and #44. We will rebase it after they are merged.

## Description
Create deployment template and scripts to deploy `TestBot` on an `Azure Linux Host`.

## Steps to configure the Pipeline
We are going to use the Windows deployment Pipeline created on #44.

1. Clone the Windows deployment Pipeline.
2. Modify the Create Bot Resource Group task to point to the linux template. Replace the BotName, AppId and AppSecret parameters with the pipeline variables.

image

3. Remove the `Compress Bot Source Code` `Powershell` task and replace it with a `Command Line` task with the following code:

``` powershell
Move $(System.DefaultWorkingDirectory)\libraries\testbot\deployment-scripts\linux\* $(System.DefaultWorkingDirectory)\libraries\testbot

git config --global user.name "BotBuilderDotNetPipeline"

git config --global user.email BotBuilderDotNet@Pipeline.com

git init

git add .

git commit -m "Add bot source code"

git remote add azure https://$(AzureDeploymentUser):$(AzureDeploymentPassword)@$(TestBotName).scm.azurewebsites.net:443/$(TestBotName).git

git push azure master
```

 Also, set the Working Directory on the advanced tab to `libraries/testbot`.
image

4. Remove the zip-push deploy line from `Create Directline` `Azure CLI` task.
image

## Testing

image

image

### CODE REVIEW

**Comment by denscollo** [comment]
I think that the steps' numbers are wrong. Last step should be number 4 instead of number 1

**Comment by GasparAcevedoZainSouthworks** [comment]
Can you blur the _Azure subscription_ in the first image?

**Comment by ParadoxARG** [comment]
Feedback applied @denscollo @GasparAcevedoZainSouthworks

**Comment by ParadoxARG** [comment]
Promoted to [#961](https://github.com/microsoft/botbuilder-js/pull/961)

**Pull request closed without merging**
